# Generated by Django 5.0.2 on 2024-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
