# Generated by Django 5.0.2 on 2024-11-02 23:53

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secrete',
            field=models.CharField(default=pyotp.random_base32, max_length=6),
        ),
    ]
