# Generated by Django 5.0.2 on 2024-11-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0002_section_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1500)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('in_progress', 'In_progress'), ('to_do', 'To_do')], default='to_do', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sections.section')),
            ],
        ),
    ]
